# blocklist
branches:
  except:
    - master

language: python

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - cd src
  - ../binaries/hugo --theme=hugo-theme-learn

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_API_KEY_TRAVIS_SPECIAL # Set in travis-ci.org dashboard
  on:
    branch: master
